name: PR Build, Lint, and Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install

      - name: Install webview-ui dependencies
        run: |
          cd webview-ui
          npm install

      - name: Build webview-ui
        run: |
          cd webview-ui
          npm run build

      - name: Lint root
        run: npm run lint

      - name: Lint webview-ui
        run: |
          cd webview-ui
          npm run lint

      - name: Run unit tests (webview-ui)
        run: |
          cd webview-ui
          npm run test

      - name: Run VSCode extension tests
        run: npm run test
